[package]
name = "RAT-discord-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.12"
serde_json = "1.0.99"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }